import 'package:flutter/material.dart';

class IconUtils {
  static IconData getIcon(String iconName) {
    final iconMap = {
      'restaurant': Icons.restaurant,
      'directions_car': Icons.directions_car,
      'shopping_cart': Icons.shopping_cart,
      'receipt': Icons.receipt,
      'movie': Icons.movie,
      'local_hospital': Icons.local_hospital,
      'local_grocery_store': Icons.local_grocery_store,
      'home': Icons.home,
      'work': Icons.work,
      'school': Icons.school,
      'fitness_center': Icons.fitness_center,
      'flight': Icons.flight,
      'card_giftcard': Icons.card_giftcard,
      'money': Icons.money,
      'phone': Icons.phone,
      'wifi': Icons.wifi,
      'power': Icons.power,
      'water_drop': Icons.water_drop,
      'local_gas_station': Icons.local_gas_station,
      'account_balance': Icons.account_balance,
      'account_balance_wallet': Icons.account_balance_wallet,
      'attach_money': Icons.attach_money,
      'credit_card': Icons.credit_card,
      'payment': Icons.payment,
      'restaurant_menu': Icons.restaurant_menu,
      'coffee': Icons.coffee,
      'fastfood': Icons.fastfood,
      'local_drink': Icons.local_drink,
      'local_taxi': Icons.local_taxi,
      'directions_transit': Icons.directions_transit,
      'directions_bike': Icons.directions_bike,
      'directions_bus': Icons.directions_bus,
      'shopping_bag': Icons.shopping_bag,
      'store': Icons.store,
      'live_tv': Icons.live_tv,
      'games': Icons.games,
      'music_note': Icons.music_note,
      'headphones': Icons.headphones,
      'medical_services': Icons.medical_services,
      'health_and_safety': Icons.health_and_safety,
      'child_care': Icons.child_care,
      'pets': Icons.pets,
      'auto_fix_high': Icons.auto_fix_high,
      'build': Icons.build,
      'electrical_services': Icons.electrical_services,
      'school': Icons.school,
      'menu_book': Icons.menu_book,
      'local_library': Icons.local_library,
      'sports': Icons.sports,
      'sports_esports': Icons.sports_esports,
    };

    return iconMap[iconName] ?? Icons.category;
  }

  static List<String> getCategoryIcons() {
    return [
      'restaurant',
      'directions_car',
      'shopping_cart',
      'receipt',
      'movie',
      'local_hospital',
      'local_grocery_store',
      'home',
      'work',
      'school',
      'fitness_center',
      'flight',
      'card_giftcard',
      'money',
      'phone',
      'wifi',
      'power',
      'water_drop',
      'local_gas_station',
      'account_balance',
      'credit_card',
      'shopping_bag',
      'store',
      'live_tv',
      'games',
      'music_note',
      'medical_services',
      'auto_fix_high',
      'school',
      'sports',
    ];
  }
}
